### ISSUE TITLE
感谢分享，T5 2.3版 mqtt不知为何无法回调

### ISSUE THREAD

**Issue by liantianji** [Eddddddddy/E-ink-esp32-arduino-weather-time-note#3]
你好up主，一直无法进群联系,故开了issues.
我上传程序后，一直无法刷新出天气，已经更换成自己的和风key

mqtt主题 notice_r 可以回调并显示在显示屏上

监听主题 weather_r 信息
weather_call_r call for weather info
{"code_1": "18", "code_2": "18", "wea_1": "小雨", "wea_2": "小雨", "tmp_1_min": "26", "tmp_1_max": "34", "tmp_2_min": "26", "tmp_2_max": "33"}

ARDUINOJSON库版本 5 和 6.9.1均使用过，一直无法解析，不知是何故。

**Comment by liantianji** [comment]
最后使用下列库版本
PubSubClient 2.8.0
ArduinoJson 6.9.1
完成解析，先前一直无法获取json触发回调。

**Comment by liantianji** [comment]
感谢up主的开源代码。
Thanks.

**Comment by Eddddddddy** [comment]
没事，能解决就行，估计是arduino的mqtt库版本问题。进群的话再申请一下。之前可能没看见。QQ：77648018
